export const expo = 
 [
      {
        "country": "Germany",
        "website": "http://www.alroko.de",
        "booth": "15",
        "phone": "+49 40 5300 450",
        "description": "Alroko is the exclusive sales representative for many important producers of industrial raw materials and machine manufacturers around the world and a reliable partner for all our customers. Our sales philosophy is to supply technically advanced products of constantly high quality, always emanating from the same established sources. Furthermore, we supply a variety of machines, mainly for producing and testing friction materials.\nMore than 30 years of experience in our business field and the man...",
        "email": "mail@alroko.de",
        "logo": "https://prelude.eurobrake.net/res/storage/exhibitor_LogoHKS_5_Claim.jpg",
        "configuration": "Space only",
        "company": "Alroko GmbH & Co KG"
      },
      {
        "country": "China",
        "website": "http://www.gdbrakes.com",
        "booth": "31",
        "phone": "+86 553 8127618",
        "description": "Anhui Guida Auto Parts Co., Ltd.(hereinafter called Guida) was established in 2010, located in the \"National Auto Parts Export Processing Base\" – Machinery Industrial Development Zone.\nGuida mainly specializes in the production of backing plate, brake steel shoe and related accessories. The products are sold all over the world.",
        "email": "goodbrakes@vip.163.com",
        "logo": "https://prelude.eurobrake.net/res/storage/exhibitor_guida__LOGO.jpg",
        "configuration": "Space only",
        "company": "Anhui Guida Auto Parts Co., Ltd"
      },
      {
        "country": "Spain",
        "website": "http://www.applusidiada.com",
        "booth": "42",
        "phone": "0034977166000",
        "description": "With over 25 years of history, Applus IDIADA is a leading engineering company providing design, testing, engineering and homologation services to the automotive industry worldwide. Applus IDIADA has more than 2.500 engineers specialized in vehicle development and an international network of subsidiaries and branch offices in 24 countries, ensuring its clients receive fast and customized services.\n\nThe headquarters, composed of a 360-hectare main technical centre which includes its own proving gr...",
        "email": "info@idiada.com",
        "logo": "https://prelude.eurobrake.net/res/storage/exhibitor_Logo_IDIADA_RGB_White.jpg",
        "configuration": "Space only",
        "company": "Applus IDIADA"
      },
      {
        "country": "Netherlands",
        "website": "http://www.asbury.com",
        "booth": "86",
        "phone": "+31 43 760 0610",
        "description": "Established in 1895, Asbury Carbons is a family owned and operated company dedicated to developing high-performance products and engineered solutions that meet the demands of traditional and emerging friction applications. As the world’s largest independent processor of carbon and graphite, and an ISO certified company, Asbury offers the largest selection of both high-quality carbon and non-carbon products.\n\nSince January 2015 Asbury operated his first European production facility in Maastricht ...",
        "email": "nlrcpnst@asbury.com",
        "logo": "https://prelude.eurobrake.net/res/storage/exhibitor_asbury-logo-color.jpg",
        "configuration": "Shell scheme",
        "company": "Asbury Graphite & Carbons NL B.V."
      },
      {
        "country": "Germany",
        "website": "http://www.atotech.com",
        "booth": "85",
        "phone": "+49 30 349 85 0",
        "description": "Atotech is one of the world’s leading manufacturers of specialty chemicals and equipment for the printed circuit board, \nIC-substrate and semiconductor industries, as well as for the decorative and functional surface finishing industries. \nAtotech has annual sales of USD1.2 billion (2017). The company is fully committed to sustainability – we develop \ntechnologies to minimize waste and to reduce environmental impact. Atotech has its headquarters in Berlin, Germany, \nand employs about 4,000 peopl...",
        "email": "info@atotech.com",
        "logo": "https://prelude.eurobrake.net/res/storage/exhibitor_Atotech_Logo.jpg",
        "configuration": "Space only",
        "company": "Atotech Deutschland GmbH"
      },
      {
        "country": "Sweden",
        "website": "http://www.acfloby.se/en/",
        "booth": "25",
        "phone": "+46 515776847",
        "description": "Automotive Components Floby was founded 1957 and delivers parts such as brake discs, wheel hubs and connecting rods to manufacturing companies all over the world. \nDriven by key values of knowledge and tradition, all the company’s products are manufactured according to the industry's highest standards in quality, precision and environmental impact. To further optimize the process for each product, AC Floby technicians work closely with customers to provide expert support and smooth workflow. AC ...",
        "email": "emil.svantesson@acfloby.com",
        "logo": "https://prelude.eurobrake.net/res/storage/exhibitor_Acfloby_bl__.jpg",
        "configuration": "Shell scheme",
        "company": "Automotive Components Floby AB"
      },
      {
        "country": "China",
        "website": "http://www.bjtysj.com/en",
        "booth": "84",
        "phone": "+86-010-82470817",
        "description": "Established in November 2009, Beijing Tianyishangjia New Material Corp., Ltd. is located in Shangzhuang Town, Haidian District, Beijing. It is a high-tech enterprise specializing in the R&D, production and marketing of brake pads and brake block series products for high-speed train, EMU, rolling stock, urban rail transit vehicle, and now has production lines of sintered brake pad, brake block and organic brake pad, brake block and other products.\nTianyishangjia has a strong strength in research ...",
        "email": "tysj@bjtysj.com",
        "logo": "https://prelude.eurobrake.net/res/storage/exhibitor_Beijing_Tianyishangjia_New_Material_Corp.__Ltd_Logo.jpg",
        "configuration": "Shell scheme",
        "company": "Beijing Tianyishangjia New Material Corp., Ltd."
      },
      {
        "country": "Germany",
        "website": "http://www.blum-novotest.com",
        "booth": "45",
        "phone": "004975160080",
        "description": "Established in 1968 and based in Ravensburg, Blum-Novotest GmbH is one of the world's leading manufacturers of high-quality measuring and testing technology for the international machine tool, aerospace and car industry. The specialist area of the measuring machines business division includes dimensional, geometry and crack testing primarily on rotationally symmetric components.",
        "email": "marketing@blum-novotest.com",
        "logo": "https://prelude.eurobrake.net/res/storage/exhibitor_Blum-Novotest_CMYK.jpg",
        "configuration": "Space only",
        "company": "Blum-Novotest GmbH"
      },
      {
        "country": "Italy",
        "website": "http://www.brembo.com",
        "booth": "0",
        "phone": null,
        "description": "Brembo is a world leader in the design, development and production of braking systems and components for cars, motorbikes, industrial vehicles, for the OE market, after-market and racing. \n\nBrembo guarantees the utmost safety and comfort and improved product performance thanks to process integration and optimisation of the entire production cycle, from the initial design and cast-iron or aluminium casting to assembly, testing and simulations on the bench, track and road.\n\nBrembo’s constant quest...",
        "email": null,
        "logo": "https://prelude.eurobrake.net/res/storage/exhibitor_brembo_logo_red185_light.jpg",
        "configuration": "Space only",
        "company": "Brembo"
      },
      {
        "country": "France",
        "website": "http://www.bruker.com\\nano",
        "booth": "27",
        "phone": "+33 01 72 86 61 04",
        "description": "Bruker is a global leader in design and manufacturing of high-performance measurement and characterization equipment. Our 3D optical microscopes and profilers, based on more than 30 years of Wyko™ technology, provide the flexible imaging and measurement capabilities for comprehensive, accurate characterization of surfaces. Bruker’s UMT mechanical testers are comprehensive and versatile systems for investigating tribology — friction, wear, load, hardness, and lubrication. Our metrology and test s...",
        "email": "productinfo.emea@bruker.com",
        "logo": "https://prelude.eurobrake.net/res/storage/exhibitor_logo_rgb_300dpi.jpg",
        "configuration": "Space only",
        "company": "Bruker Nano Surfaces"
      },
      {
        "country": "Taiwan",
        "website": "http://www.bsstec.com.tw",
        "booth": "73",
        "phone": "+88662018988",
        "description": "BSS TEC is a professional braking components manufacturer which originally focused on fine backing plates. With a customized progressive press and an experienced, professional team we created the BSS Stamping technology to manufacture the fine backing plates. In 2017, we expanded our scale and acquired a shoe core company which has more than 40 years of experience and the widest range in Taiwan.\nWith our innovation and professional ability, we never stop improving ourselves and pursuing the high...",
        "email": "bss@bsstec.com.tw",
        "logo": "https://prelude.eurobrake.net/res/storage/exhibitor_BSStec_LOGO_white.jpg",
        "configuration": "Shell scheme",
        "company": "BSS Tec International Corporation"
      },
      {
        "country": "Italy",
        "website": "http://www.camesrl.eu",
        "booth": "52",
        "phone": "0039 02 9644651",
        "description": null,
        "email": "info@camesrl.eu",
        "logo": "https://prelude.eurobrake.net/res/storage/exhibitor_Logo_CAME_JPG__senza_your_partner_.jpg",
        "configuration": "Shell scheme",
        "company": "Came S.r.l"
      },
      {
        "country": "Belgium",
        "website": "http://www.cardolite.com",
        "booth": "12",
        "phone": "003292658826",
        "description": "Cardolite Corporation is a privately held developer and manufacturer of the world’s largest variety of products derived from cashew nutshell liquid (CNSL), a renewable natural resource. The unique properties of CNSL are used to develop and produce a wide range of products to service the coating, friction material, adhesive, composite and foam markets.\n\nAt Eurobrake Cardolite will be presenting it’s latest innovations for the friction materials industry. Think high performance brown friction part...",
        "email": "frederique.catterman@cardolite.com",
        "logo": "https://prelude.eurobrake.net/res/storage/exhibitor_Cardolite_Logo_Slogan.jpeg",
        "configuration": "Shell scheme",
        "company": "Cardolite Speciality Chemicals Europe NV"
      },
      {
        "country": "Germany",
        "website": "http://www.ceramtec.com",
        "booth": "83",
        "phone": "+497163166239",
        "description": "Your Brake Parts - Our Competence in Machining and Materials\n\nSPK Cutting Tool Division of CeramTec GmbH can call on their knowledge and experience of high performance machining of cast iron especially in the brake industry for nearly 60 years. These are the best qualifications for solving the whole range of machining tasks with optimal cutting tools and best in class cutting materials based on ceramics and PCBN. \nOur machining competence and application of cutting tools is not limited to brake ...",
        "email": "info@ceramtec.de",
        "logo": "https://prelude.eurobrake.net/res/storage/exhibitor_Logo_CeramTec_Vollton__Konvertiert_.jpg",
        "configuration": "Space only",
        "company": "CeremTec GmbH"
      },
      {
        "country": "China",
        "website": "http://www.cocangraphite.com",
        "booth": "92",
        "phone": "+86 27 8265 3636",
        "description": "We, Cocan Graphite, have grown up as a leader in Chinese powder carbon and graphite industry. Our product portfolios range from graphite to coke, from synthetic to natural types of carbonaceous materials. We dedicate to continuously improving our production technologies and processing systems in decades to come. All our inbound raw materials and outbound finished products are carefully tested and certified by our cutting-edge laboratory – Cocan Carbon Center. With ISO 9001:2015 certification, we...",
        "email": "info@cocangraphite.com",
        "logo": "https://prelude.eurobrake.net/res/storage/exhibitor_Cocan_Graphite.jpg",
        "configuration": "Shell scheme",
        "company": "Cocan Graphite"
      },
      {
        "country": "Italy",
        "website": "http://www.comec-grinders.com",
        "booth": "59",
        "phone": "+39 0523 640 211",
        "description": "Founded in 1963, COMEC specializes in the design and manufacturing of grinding machines for special applications. In the last 30 years, COMEC focused especially on developing Grinding & Pressing Technologies for the Friction Material Industry. \n\nBecause of the excellent technological solutions, developed through both internal research & development and working side by side with its customers, COMEC is a top leading supplier worldwide of grinding machines for friction materials. \n\nWe are continuo...",
        "email": "comec@comec-grinders.com",
        "logo": "https://prelude.eurobrake.net/res/storage/exhibitor_Logo_Comec001.jpg",
        "configuration": "Space only",
        "company": "COMEC Grinding Machines & Presses"
      },
      {
        "country": "Italy",
        "website": "http://www.daicospa.com",
        "booth": "82",
        "phone": "390119204101",
        "description": "DAICO AUTOMOTIVE PRODUCTS S.P.A. is the European leading Company, manufacturer and distributor of brake hardware for Automotive Industries and brake industries, since 1987. Products: components and accessories for disc and drum brake systems and for brake calipers. Application: Passenger Cars, L.C.V. and C.V.\n\nProduct range:\n- Brake pad and brake caliper hardware for passenger vehicles: piston clips, wire springs, acoustic wear sensors, counterweights, etc.\n- Brake caliper hardware: sliding pad ...",
        "email": "s.parente@daicospa.com",
        "logo": "https://prelude.eurobrake.net/res/storage/exhibitor_logo_daico.jpg",
        "configuration": "Shell scheme",
        "company": "Daico Automotive Products S.p.A."
      },
      {
        "country": "Japan",
        "website": "http://www.daishinkako.com",
        "booth": "71",
        "phone": "+81 334 358 561",
        "description": "Daishin Kako Company Ltd is based in Tokyo and has over fifty years’ experience of designing, manufacturing and continuously developing lubricating products for highly specific applications. One of those applications in which Daishin’s expertise lies, is in the field of automotive brake squeal reduction. Daishin has been studying the use of greases and other lubricating materials used for the prevention of brake noise and squeal for over forty years. Daikalub 528D is the latest development in th...",
        "email": "info@daishinkako.com",
        "logo": "https://prelude.eurobrake.net/res/storage/exhibitor_Daishin_Kako_Logo.jpg",
        "configuration": "Shell scheme",
        "company": "Daishin Kako Co Ltd"
      },
      {
        "country": "Finland",
        "website": "http://www.dekati.com",
        "booth": "48",
        "phone": "+35833578100",
        "description": "Dekati Ltd. is a world leader in designing and manufacturing innovative fine particle measurement solutions. We have over 25 years of experience in providing measurement instruments and complete measurement solutions to a wide variety of environments and sample conditions. We take pride in the quality and robustness of our products and are committed to finding the best possible solution for your aerosol measurement needs. Our experience and expertise in aerosol measurement applications is at you...",
        "email": "sales@dekati.fi",
        "logo": "https://prelude.eurobrake.net/res/storage/exhibitor_DekatiLogo2013medium.jpg",
        "configuration": "Space only",
        "company": "Dekati Ltd"
      },
      {
        "country": "Germany",
        "website": "http://www.eirich.com",
        "booth": "75",
        "phone": "+49 6283510",
        "description": "EIRICH develops and manufactures machines and equipment for industrial processing technology with processes such as granulation , drying and, in particular, mixing and fine grinding. Depending on the industry, the family enterprise offers its customers stand-alone machines with process peripherals right through to turnkey processing plants . The company has been operating in industrial mixing technology for over 100 years. The portfolio includes mixers for industrial applications with a volume o...",
        "email": "eirich@eirich.de",
        "logo": "https://prelude.eurobrake.net/res/storage/exhibitor_EIRICH_Logo.jpg",
        "configuration": "Shell scheme",
        "company": "EIRICH"
      },
      {
        "country": "Germany",
        "website": "http://www.erdrich.de",
        "booth": "19",
        "phone": "+49 784 370 50",
        "description": "Erdrich Umformtechnik is one of the world's leading manufacturers of metal brake pistons and specific foundation \nrelated parts for the automotive industry. The Business Unit Brake Piston has facilities in Germany, Czech Republic, Georgia/USA\nand China producing several 10 Mio. pistons per year with a global footprint. The piston portfolio\ncomprises diameters from 36 to 66 mm for front and rear axle applications. All pistons are optimized to minimum weight at maximum\nstrength using our enhanced ...",
        "email": "info@erdrich.de",
        "logo": "https://prelude.eurobrake.net/res/storage/exhibitor_ERDRICH_LOGO_4C.jpg",
        "configuration": "Shell scheme",
        "company": "Erdrich Umformtechnik"
      },
      {
        "country": "Germany",
        "website": "http://www.erlmann.de",
        "booth": "64 & 65",
        "phone": "+49 236 618 010",
        "description": "ERLMANN – we are one of the world's leading manufacturers of drilling and grinding machines for the major friction material producers! \nWhether standard machines or customer-specific solutions –our quality convinces!\n\nFor more than 60 years our products have been valued by the major friction\nmaterial producers world-wide. The company has been founded in 1955 by the Engineer Ferdinand Erlmann. Due to his former activities he had best contacts to the Brake Lining and Clutch Facing Industry in Germ...",
        "email": "info@erlmann.de",
        "logo": "https://prelude.eurobrake.net/res/storage/exhibitor_ERLMANN_logo.jpg",
        "configuration": "Space only",
        "company": "ERLMANN GmbH & Co. KG"
      },
      {
        "country": "Austria",
        "website": "http://www.frimeco.com",
        "booth": "22",
        "phone": "+4312183930",
        "description": "FRIMECO - High-quality raw materials for the global friction industry\nSince 1995, FRIMECO has been producing and marketing high quality materials for the international friction industry, supplying from our global manufacturing facilities to the whole world.\nFRIMECO products are used in friction linings in the automotive, railway, and industrial sectors.\nAmong FRIMECO’s many products, you will find synthetic and mineral metal sulfides as well as steel fibers, non-ferrous metal fibers and cashew-d...",
        "email": "doris.schmerlaib@frimeco.com",
        "logo": "https://prelude.eurobrake.net/res/storage/exhibitor_Frimeco_mit_slogan.jpg",
        "configuration": "Shell scheme",
        "company": "Frimeco"
      },
      {
        "country": "Germany",
        "website": "http://www.fritzwinter.de",
        "booth": "54",
        "phone": "+49 642 878 230",
        "description": "The Fritz Winter Foundry is supplier and partner for the global automotive, commercial vehicle and hydraulic industry. We develop and manufacture rough and finish part components as well as complex system components, increasingly in light-weight design also.\n\nWith our innovative production concepts which we continuously develop further, we provide already today the mobility of tomorrow. Our material basis is sustainable as we use recycled iron as raw material for our High-Tech products. The self...",
        "email": "sales@fritzwinter.de",
        "logo": "https://prelude.eurobrake.net/res/storage/exhibitor_FW_Logo_eng_300dpi_RGB.jpg",
        "configuration": "Space only",
        "company": "Fritz Winter"
      },
      {
        "country": "Germany",
        "website": "http://www.gk-graphite.com",
        "booth": "99",
        "phone": "+49 8586 609 0",
        "description": "Graphit Kropfmühl, with its worldwide subsidiaries, has more than 140 years of tradition and expertise in graphite. With our technical competence to create solutions, our market proximity, and absolute customer orientation we have become a trend-setting graphite refiner.\nOn the basis of innovative and quality-conscious high-technology and through intensive dialogue with customers and partners, we develop high-quality special products. In order to secure the supply of raw materials we hold shares...",
        "email": "info@gk-graphite.com",
        "logo": "https://prelude.eurobrake.net/res/storage/exhibitor_AMG_Graphite_2-01.jpg",
        "configuration": "Shell scheme",
        "company": "Graphit Kropfmühl GmbH"
      },
      {
        "country": "United States",
        "website": "http://www.greeninginc.com",
        "booth": "64 + 65",
        "phone": "+1 313 366 7160",
        "description": "GREENING’s dynamometers and test equipment and ISO certified testing services span a wide range of vehicle brake system and driveline components, including automobile, commercial vehicle, motorcycle, aviation, industrial, military, and marine applications. Our Detroit-based lab regularly conducts tests in accordance with SAE, JASO, ISO, and other industry and corporate procedures. Additionally, our long-standing experience in motorsports brake testing has assisted race teams across the world. GR...",
        "email": "dcandela@greeninginc.com",
        "logo": "https://prelude.eurobrake.net/res/storage/exhibitor_Greening_logo.jpg",
        "configuration": "Space only",
        "company": "Greening Inc."
      },
      {
        "country": "Mexico",
        "website": "http://www.hascor.com/",
        "booth": "4",
        "phone": null,
        "description": "Hascor International Group - Your trusted source for Nitrogen Bearing Ferro Alloys & Metal Powders. \nHascor International Group is now proudly offering all types of Titanates including Fibre-free and many more. We also offer Iron powder and Graphite powder. Founded in 1993, our group has, in a few short years, earned an excellent reputation for performance & consistent, repeatable quality. Our group is committed to reinvesting our profits to grow our product lines and to make Hascor the most eff...",
        "email": null,
        "logo": "https://prelude.eurobrake.net/res/storage/exhibitor_Hascor_Logo.jpg",
        "configuration": "Shell scheme",
        "company": "Hascor Metals SA DE CV"
      },
      {
        "country": "Germany",
        "website": "http://www.head-acoustics.de",
        "booth": "33",
        "phone": "+49 2407 577 0",
        "description": "HEAD acoustics GmbH is one of the world’s leading companies for integrated acoustic solutions as well as sound and vibration analysis. The company benefits from the combination of cutting-edge measurement technology with many years of practical experience in the industry. HEAD acoustics is receiving global accolades for its expertise and its pioneering role in the development of hardware and software for the measurement and analysis for the optimization of sound quality.\nEspecially in the field ...",
        "email": "info@head-acoustics.de",
        "logo": "https://prelude.eurobrake.net/res/storage/exhibitor_HEAD_Firmenzeichen_blau.jpg",
        "configuration": "Shell scheme",
        "company": "HEAD acoustics GmbH"
      },
      {
        "country": "Germany",
        "website": "http://www.horiba.com",
        "booth": "35",
        "phone": "+49 615 150 000",
        "description": "Shaping the automotive industry by developing promising and unique innovations – this is the core of all our activities. HORIBA Automotive Test Systems is your strong partner offering total solutions paired with unrivalled know-how and innovative spirit while being able to tailor each solution to customer-specific demands – from simple testing capacities to complex orders.\n\nNo matter which type of braking system is to be tested, the experienced team of Contract Test Engineers handles customers’ ...",
        "email": "info@horiba.de",
        "logo": "https://prelude.eurobrake.net/res/storage/exhibitor_HORIBA-Logo-RGB-1024x167.jpg",
        "configuration": "Shell scheme",
        "company": "HORIBA Europe GmbH"
      },
      {
        "country": "Austria",
        "website": "http://www.iag.at",
        "booth": "78",
        "phone": "+43 2622 21734/0",
        "description": "Your Specialist in innovative Friction Lining Technology\n\nOur friction lining presses are employed in the manufacturing of high-quality brake pads that fulfil every quality requirement specified by customers. Our customers, leading global players in the friction lining industry need to continuously face new technological and economic challenges\n\nWe offer hot and cold /short pressing technology according to your particular needs.\n\nPresses\nRotary type press - Stand-alone production machine for big...",
        "email": "sales@iag.at",
        "logo": "https://prelude.eurobrake.net/res/storage/exhibitor_IAG_logo.jpg",
        "configuration": "Shell scheme",
        "company": "IAG Industrie Automatisierungs GmbH"
      },
      {
        "country": "France",
        "website": "http://www.imerys.com",
        "booth": "81",
        "phone": null,
        "description": "Imerys is the world leader in mineral-based specialties for friction materials, delivering high value- added, functional solutions for both resin-bonded and copper-sintered brakes.\nThe Group draws on its knowledge of applications,scientific expertise and technological know-how to offer s beneficiating its mineral resources, produce synthetic minerals and develop formulations. Imerys thus contributes essential properties to customers’ products and performance, such as minimum fade, low NVH, and w...",
        "email": null,
        "logo": null,
        "configuration": "Shell scheme",
        "company": "Imerys"
      },
      {
        "country": "Italy",
        "website": "http://www.imfeng.eu/",
        "booth": "62",
        "phone": "+39 023 391 088 0",
        "description": "Thanks to almost 20 years of experience in the friction industry, IMF ENGINEERING design completely automatic painting systems, consisting of: painting booth in stainless steel or in antistatic PVC, infrared or convection oven, both electric and gas, cooling systems. All elements are connected to each other in a few meters. The loading and unloading systems can be both robotic and manual, according to the customer’s needs.\n\nThe painting booth is specifically designed for the brake pads which, to...",
        "email": "info@imfeng.eu",
        "logo": "https://prelude.eurobrake.net/res/storage/exhibitor_IMF_Eng_400dpi.jpg",
        "configuration": "Space only",
        "company": "IMF Engineering S.r.l"
      },
      {
        "country": "United States",
        "website": null,
        "booth": "17",
        "phone": null,
        "description": null,
        "email": null,
        "logo": null,
        "configuration": "Shell scheme",
        "company": "Industrial Measurement Systems Inc"
      },
      {
        "country": "Germany",
        "website": "http://www.InfraTec.de",
        "booth": "40",
        "phone": "+49 3518718620",
        "description": "The Dresden-based company InfraTec GmbH Infrarotsensorik und Messtechnik is a specialist for products and services in the field of infrared technology. It is active in all areas of thermographic applications, with its scope of performance ranging from the sales of thermographic cameras to the supply of thermal imaging systems and turn-key thermographic automation solutions. One of these solutions regarding the automotive industry is Thermal Rotate Check (TRC) – a thermography based test bench so...",
        "email": "a.krausz@infratec.de",
        "logo": "https://prelude.eurobrake.net/res/storage/exhibitor_Logo-InfraTec-RGB.jpg",
        "configuration": "Space only",
        "company": "Infra Tec GmbH Infrarotsensorik und Messtechnik"
      },
      {
        "country": "Germany",
        "website": "http://www.intes.de",
        "booth": "29",
        "phone": "+49 7117849918",
        "description": "INTES is your competent partner for all aspects of numerical simulation using Finite Elements (FE). INTES develops and markets the standard software PERMAS to perform FE analysis tasks. \n\nPERMAS enables the engineer to perform comprehensive analyses and simulations in many fields of applications like stiffness and stress analysis, contact analysis, vibrations, acoustic simulations, heat transfer, different kinds of optimization including topology, shape and sizing, as well as rotordynamics and r...",
        "email": "info@intes.de",
        "logo": "https://prelude.eurobrake.net/res/storage/exhibitor_intes-n.jpg",
        "configuration": "Space only",
        "company": "INTES GmbH"
      },
      {
        "country": "Italy",
        "website": "http://www.itaprochim.it",
        "booth": "79",
        "phone": "+39 025 730 3726",
        "description": "Itaprochim, leader in the Friction Industries, develops and produces raw materials based on it's own technology.\nItaprochim has always been focused on the research and development of new materials and technologies.\n\nOur goal is to provide customers with a range of raw materials and auxiliary goods from reliable and qualified sources.",
        "email": "info@itaprochim.it",
        "logo": "https://prelude.eurobrake.net/res/storage/exhibitor_ITA.JPG",
        "configuration": "Shell scheme",
        "company": "Itaprochim SRL"
      },
      {
        "country": "Italy",
        "website": null,
        "booth": "44",
        "phone": "+39 0119250359",
        "description": "ITT Fine Blanking is a back-plate supplier for brake pads destined to passenger cars, vans and truck applications.\nThere are around 1.500 different references of back plates produced and distributed to the main European, American and Asiatic car manufacture brands.\nITT Fine Blanking operates in a proactive and serious way to provide solutions that address and exceed customers' expectations for safety, performance and comfort.\nITT Fine blanking is the only Fine Blanking Company that uses in its p...",
        "email": "stefano.demaria@itt.com",
        "logo": "https://prelude.eurobrake.net/res/storage/exhibitor_ITT_Fine_Blanking_Company_Logo.jpg",
        "configuration": "Shell scheme",
        "company": "ITT Fine Blanking"
      },
      {
        "country": "Italy",
        "website": "http://www.itt.com/home",
        "booth": "49",
        "phone": "+39 0175 347 111",
        "description": "ITT is a diversified leading manufacturer of highly engineered critical components and customized technology solutions for growing global sectors in energy, transportation and industrial markets. ITT’s Friction Technologies develops, produces, and sells brake pads and friction materials for private and public transportation markets and major automotive manufacturing industries around the world. They are a leading supplier of technological innovations in automotive R&D services and are recognized...",
        "email": "Keiko.Claassen@itt.com",
        "logo": "https://prelude.eurobrake.net/res/storage/exhibitor_ITT_Friction_Technologies.jpg",
        "configuration": "Space only",
        "company": "ITT Friction Technologies"
      },
      {
        "country": "United Kingdom",
        "website": "http://www.durransgroup.com",
        "booth": "60",
        "phone": "01226370000",
        "description": "The James Durrans Group is a family owned group of companies established in 1863 with the head office at Penistone, Sheffield in England and three other UK manufacturing sites at, Bilston (West Midlands), Brancepeth (Co. Durham) and Scunthorpe, (Lincolnshire). The group markets a complete range of Carbon based materials supplying to a wide range of industries globally.\n\nJames Durrans Friction Division offers a full range of carbon based materials to the friction industry. Supplying to Original E...",
        "email": "sbostwick@durrans.co.uk",
        "logo": "https://prelude.eurobrake.net/res/storage/exhibitor_Logo_klein_2.JPG",
        "configuration": "Shell scheme",
        "company": "James Durrans & Sons"
      },
      {
        "country": "Austria",
        "website": "http://www.kmi.at",
        "booth": "23",
        "phone": "+43435254535",
        "description": "KMI is leading global supplier of lamellar MIOX and producer of Wollastonite, Mica Muscovite, Mica Phlogopite and Talc. These functional minerals are used in various industries such as friction materials and brake pads, polymers, coatings and ceramics. As a specialist in micronization of mineral raw materials KMI produces high quality functional fillers in a particle size range of 1µm - 1mm and is focused on high aspect ratios.\nThe products of KMI contribute to the wide range of raw materials fo...",
        "email": "g.kert@kmi.at",
        "logo": "https://prelude.eurobrake.net/res/storage/exhibitor_KMI_Logo__300_dpi_.jpg",
        "configuration": "Space only",
        "company": "Karntner Montanindustrie GmbH"
      },
      {
        "country": "United Kingdom",
        "website": "http://www.kommerlinguk.com",
        "booth": "34",
        "phone": "+44 7774450813",
        "description": "Kommerling UK (an H B Fuller Company) have been supplying bonding agents to the Friction Industry for over 15 years. All the products, produced in the UK, are water based to meet the environmental requirements of our customers and designed to pass the demanding Automotive test specifications for Hot and Cold Shear, with application by either roller or spray. A complete range of products for other elastomer to substrate requirements is also available see www.kommerlinguk.com",
        "email": "garmiger@kommerlinguk.com",
        "logo": "https://prelude.eurobrake.net/res/storage/exhibitor_H.B.Fuller-Cilbond-NoTag-CobrandedLogo-RGB.JPG",
        "configuration": "Space only",
        "company": "Kommerling UK"
      },
      {
        "country": "Netherlands",
        "website": "http://www.lapinus.com/friction",
        "booth": "32",
        "phone": "+31 475 35 35 55",
        "description": "At Lapinus, we offer premium quality stone fibres and strong technical support for the friction industry. We go beyond being raw material supplier by researching the functionalities of our products together with other materials in the friction matrix. Rise to global challenges for friction, our team has continuously driven innovation for better solutions together with our customers. Rooted in sustainability, our highly biosoluble products contribute to shaping a better world for today and tomorr...",
        "email": "mike.palmen@lapinus.com",
        "logo": "https://prelude.eurobrake.net/res/storage/exhibitor_LapinusLogo-PrimaryColour.jpg",
        "configuration": "Shell scheme",
        "company": "Lapinus"
      },
      {
        "country": "Germany",
        "website": "http://www.liqfric.com",
        "booth": "30",
        "phone": "021431383030",
        "description": "The company was founded in 2016 and is based in Leverkusen, Germany. The company develops, manufactures and sells liquid friction compounds to manufacture brake- and clutch-friction materials. The uniqueness of these products lies in the ease of application and pressure-less form giving. The company was awarded Second Place in Best Poster Competition at EB 2018 for 3D Printed Friction Material.",
        "email": "info@liqfric.com",
        "logo": "https://prelude.eurobrake.net/res/storage/exhibitor_LIQFRIC-Logo.jpg",
        "configuration": "Shell scheme",
        "company": "LF GmbH & Co. KG"
      },
      {
        "country": "Germany",
        "website": "http://www.linkeng.com",
        "booth": "74 & 76",
        "phone": "+49 734 453 0800",
        "description": "Established in 1935, Link Engineering Company is the global leader in designing and manufacturing a complete range of test systems and in providing test services to the transportation industry in the areas of brake, transmission, driveline, steering, wheel, hub, tire, bearing, and electric motor applications. Headquartered in Plymouth, Michigan (suburb of Detroit), LINK operates facilities providing test services, test system sales, and customer support across the United States, Brazil, China, J...",
        "email": "m.betts@linkeng.com",
        "logo": "https://prelude.eurobrake.net/res/storage/exhibitor_JPG_Logo_CMYK_Print_Use.jpg",
        "configuration": "Space only",
        "company": "Link Engineering Company"
      },
      {
        "country": "China",
        "website": "http://www.lyhongtu.com.cn",
        "booth": "7",
        "phone": "+86 137 343 697 36",
        "description": "LINYI HONGTU ELECTRON CO., LTD is a leading manufacturer of brake pad wear sensor and a reliable supplier of ABS sensor and brake pad accessories in China.\n\n“HONGTU” has become a top brand of brake pad wear sensor in China and European countries. Thanks to our excellent reputation, our quality standards and our highly competitive prices, we export successfully to more than 40 countries. Over 40% are with final destination O.E. or O.E.S. We produce more than 1000 references for both passenger car...",
        "email": "leo@lyhongtu.com.cn",
        "logo": "https://prelude.eurobrake.net/res/storage/exhibitor_htu_logo.jpg",
        "configuration": "Shell scheme",
        "company": "Linyi Hongtu Electron Co. Ltd"
      },
      {
        "country": "Germany",
        "website": "http://www.loedige.de",
        "booth": "16",
        "phone": "004952513090",
        "description": "Lödige is a global leading supplier of mixers, coating systems, granulators, dryers and reactors. As the inventor of the Ploughshare Mixers, Lödige has decades of experience in the process technology. Machines and process systems are at home in the pharmaceutical and food industry just as well as in the building materials industry, environment, minerals and ores but also chemicals and plastics.\nLödige is specialised in the industrial mixing, drying, reacting, coating and granulating. Lödige deal...",
        "email": "info@loedige.de",
        "logo": "https://prelude.eurobrake.net/res/storage/exhibitor_LoedigeLogo.jpg",
        "configuration": "Shell scheme",
        "company": "Lödige Process Technology"
      },
      {
        "country": "Turkey",
        "website": "http://www.logel.com.tr",
        "booth": "46",
        "phone": "+90 262 7512200",
        "description": "Founded in 1983, our company has succeeded in becoming a customer-focused organization strengthening its infrastructure through Kaizen activities, strategic targets and plans and the most successful examples of the machinery sector ever since its foundation. It continues its operations based on this principle. It has reached significant achievements between the past and the future. The company is involved in new projects and presents the market its disc brake pads for heavy vehicles, light comme...",
        "email": "info@logel.com.tr",
        "logo": "https://prelude.eurobrake.net/res/storage/exhibitor_pwr_logo.jpg",
        "configuration": "Shell scheme",
        "company": "LOGEL MAKINE OTOMOTIV SANAYI VE TICARET A.S."
      },
      {
        "country": "Poland",
        "website": "http://www.lumag.pl",
        "booth": "53",
        "phone": "+48672844822",
        "description": "LUMAG was founded in 1988 by Marek Zak, the current main shareholder and CEO. Initially we focused on the production of brake linings. Later we implemented our own brake pad manufacturing technology.\nOver the years the company achieved enormous technological progress, which is showcased by or constantly upgraded collection of machinery, applied engineering solutions as well as the continuous rise of quality and safety standards.\nApart from the friction materials production, Lumag company produce...",
        "email": "lumag@lumag.pl",
        "logo": "https://prelude.eurobrake.net/res/storage/exhibitor_Lumag_CI-5.jpg",
        "configuration": "Shell scheme",
        "company": "Lumag Sp. z o.o."
      },
      {
        "country": "Italy",
        "website": "http://www.magyc.it",
        "booth": "37",
        "phone": "+390332701775",
        "description": "Founded in 2001, Magyc is specialized in design and manufacturing of High Precision Testing and Measurement Systems for Industrial Quality Control. Magyc today counts on over 15 years of experience in product and process innovation, quality control, assurance systems, problem analysis and customized solutions. Thanks to its know-how and the collaboration with the most innovative industries and research institutes, MaGyc is today a leader of the quality control in industrial sector, through its s...",
        "email": "info@magyc.it",
        "logo": "https://prelude.eurobrake.net/res/storage/exhibitor_MAGYC_logo_ritaglio_105x275.jpg",
        "configuration": "Shell scheme",
        "company": "MaGyc s.r.l."
      },
      {
        "country": "Germany",
        "website": "https://www.mann-hummel.com/en/",
        "booth": "68",
        "phone": null,
        "description": "About MANN+HUMMEL\n MANN+HUMMEL is a leading global expert for filtration solutions. The company group with its headquarters in Ludwigsburg, Germany, develops solutions for motor cars, industrial applications, clean air in interior spaces and the sustainable use of water. In 2017 the group achieved sales of approx. 3.9 billion euros worldwide with more than 20,000 employees at more than 80 locations. The products manufactured by the group include air cleaner systems, intake manifold systems, liqu...",
        "email": "vanessa.tietze@mann-hummel.com",
        "logo": "https://prelude.eurobrake.net/res/storage/exhibitor_MH_Logo_RGB.jpg",
        "configuration": "Shell scheme",
        "company": "MANN+HUMMEL GmbH"
      },
      {
        "country": "Denmark",
        "website": "http://www.meneta.com",
        "booth": "43",
        "phone": "(+45) 6618 8934",
        "description": "From our beginnings in 1953 as a local toolmaker and punching workshop, we have grown to become a global supplier of high-quality braking components for the automotive industry. Today, we are over 2,000 employees in Europe, Asia, and North America. We design, test, and produce millions of brake shims, backplates, and brake components each year.\n\nFOR OVER 65 YEARS, MENETA HAS DELIVERED\n\nTECHNOLOGY\nOur innovation is the result of world-class materials know-how, unique testing capabilities, and qua...",
        "email": "sales@meneta.com",
        "logo": "https://prelude.eurobrake.net/res/storage/exhibitor_menta_group_logo.jpg",
        "configuration": "Space only",
        "company": "MENETA Group"
      },
      {
        "country": "United Kingdom",
        "website": null,
        "booth": "18",
        "phone": null,
        "description": null,
        "email": null,
        "logo": null,
        "configuration": "Space only",
        "company": "Microface Ltd"
      },
      {
        "country": "Germany",
        "website": null,
        "booth": "21",
        "phone": null,
        "description": null,
        "email": null,
        "logo": null,
        "configuration": "Space only",
        "company": "Mineralmuhle Leun Rau GmbH"
      },
      {
        "country": "United States",
        "website": "http://www.morganthermalceramics.com",
        "booth": "56",
        "phone": "7067964313",
        "description": "At Morgan Advanced Materials we manufacture and deliver fibres which are blended into friction formulations producing stable friction without noise, no wheel dust, and improved pad and rotor life over a wide range of temperature, pressure, and speed. \nOur extensive experience working with customers all over the world to engineer, design and manufacture high performance fibres in operating environments from 500°C to 1600°C. We have a proven track record for helping customers to improve products a...",
        "email": "Wendy.Evans@morganplc.com",
        "logo": "https://prelude.eurobrake.net/res/storage/exhibitor_MASTER_L-H_MGAM_LOGO_08.02.13.jpg",
        "configuration": "Shell scheme",
        "company": "Morgan Advanced Materials"
      },
      {
        "country": "France",
        "website": "http://www.nofmetalcoatings.com",
        "booth": "50",
        "phone": "+33 344 646 362",
        "description": "NOF METAL COATINGS Group is the pioneer in zinc flake coatings for metal corrosion protection and develops waterborne chemicals contributing to reduce impacts on the environment, health and security of people. \n\nNOF METAL COATINGS Group aims at sustainable developments by decreasing impressively V.O.C. and CO2 emissions, complying with environmental directives and withdrawing products harmful to health.\n\nAn intensive industrial and research footprint in Asia, Europe and America allows us to work...",
        "email": "infofr@nofmetalcoatings.com",
        "logo": "https://prelude.eurobrake.net/res/storage/exhibitor_nof_metal_coatings_group_logo-2lignes.jpg",
        "configuration": "Space only",
        "company": "NOF METAL COATINGS EUROPE S.A."
      },
      {
        "country": "Canada",
        "website": "http://WWW.NRSBRAKES.COM",
        "booth": "55 & 58",
        "phone": "+14 164 941 444",
        "description": "NRS™ is NUCAP Industries’ patented process for the surface modification of disc brake backing plates, adding a consistent matrix of raised steel hooks that facilitate a mechanical bond between disc brake plate and friction materials. The NRS™ hooks provide mechanical bonding while exceeding industry requirements for heat, shear and environmental delamination protection.\n\nNRS™ is often called “the hidden benefit”, essentially invisible on a finished brake pad while delivering brake products that;...",
        "email": "info@nucap.com",
        "logo": "https://prelude.eurobrake.net/res/storage/exhibitor_NRS_Safe_Galvanized__300dpi_.jpg",
        "configuration": "Space only",
        "company": "NUCAP Industries Inc."
      },
      {
        "country": "Japan",
        "website": "http://www.otsukac.co.jp",
        "booth": "13",
        "phone": "+81 352 972 727",
        "description": "Otsuka Chemical manufactures various types of Titanate (TISMO, TERRACESS) and its plastic compounds (POTICON).\nThe benefits of TERRACESS are as follows: \n1) Stabilization of the effectiveness\n2) Improvement of the NVH performance \n3) Low wear both rotor and pad\nTERRACESS itself, brake pad and rotor after test and typical data will be exhibited.",
        "email": "occ.gs@otsuka.jp",
        "logo": "https://prelude.eurobrake.net/res/storage/exhibitor_Otsuka_Chemicals.jpg",
        "configuration": "Shell scheme",
        "company": "Otsuka Chemical Co"
      },
      {
        "country": "Germany",
        "website": "http://www.pallmann.eu",
        "booth": "38",
        "phone": "+49 63328020",
        "description": "PALLMANN specializes in size reduction and offers the widest range of machines and complete Systems for successful preparation of all soft to medium hard, brittle, tough, elastic or fibraous materials. As pioneers in the field of size reduction, we have made an important contribution to today's State of the Art of size reduction and material preparation techniques resulting in numerous patents. The technical Solutions of PALLMANN contribute to an optimaized utilization of existing resources and ...",
        "email": "Paul-Kenneth.Amas@Pallmann.eu",
        "logo": "https://prelude.eurobrake.net/res/storage/exhibitor_PALLMANN_Logo_RGB.JPG",
        "configuration": "Space only",
        "company": "PALLMANN Maschinenfabrik GmbH & Co.KG"
      },
      {
        "country": "United States",
        "website": "http://www.palmerint.com",
        "booth": "72",
        "phone": "+1 610 584 4241",
        "description": "Palmer International has been developing and manufacturing innovative products based on Cashew Nutshell Liquid (CNSL) for the global automotive friction material industry for over fifty years. Our liquid and solid particle CNSL products are found in formulations from motorcycles to trains and everything in between. Please stop by our booth to learn about our new manufacturing plant in India.\n\nPalmer...Innovation in a Nutshell!",
        "email": "info@palmerint.com",
        "logo": "https://prelude.eurobrake.net/res/storage/exhibitor_PILogoGreen.JPG",
        "configuration": "Shell scheme",
        "company": "Palmer International"
      },
      {
        "country": "Germany",
        "website": "http://www.polytec.com",
        "booth": "39",
        "phone": "+4972436040",
        "description": "Polytec develops and manufactures high-quality optical measurement solutions for the non-contact analysis of vibration and dynamics, speed and length in production processes as well as for surface topography. As premium supplier the company advances its customers measurements in research, development and manufacturing.\nWith 50 years of expertise and more than 400 employees, Polytec presents with their 3D Scanning Vibrometers the globally established gold-standard for experimental and operational...",
        "email": "info@polytec.de",
        "logo": "https://prelude.eurobrake.net/res/storage/exhibitor_Pol_logo_2008_25m100y.jpg",
        "configuration": "Shell scheme",
        "company": "Polytec GmbH"
      },
      {
        "country": "Italy",
        "website": "http://www.pometon.com",
        "booth": "93",
        "phone": "+39 041 290 3611",
        "description": "Pometon, founded in 1940, is today the largest European producer of water-atomized copper, and has skills and systems to retain its customers on multiple application fronts producing with three different structures, ferrous powders, non-ferrous and stainless-steel shots. \nThe Headquarters based in Maerne, Venice, controls three subsidiaries in Europe (UK, Spain and Germany) and two in Asia (India and Turkey), all equipped with warehouse, a second production site in Serbia for electrolytic copper...",
        "email": "marketing@pometon.com",
        "logo": null,
        "configuration": "Shell scheme",
        "company": "Pometon S.p.A."
      },
      {
        "country": "Belgium",
        "website": "http://www.procotex.com",
        "booth": "95",
        "phone": "+32 56 48 38 88",
        "description": "Procotex Corporation S.A. based in Dottignies, (BE), with factories in Lithuania, Turkey, Belgium and France. We are specialized in flax hackling, synthetic, natural & technical fibers recycling. Via its subsidiary Apply Carbon sa in France, Procotex offers and entire range of carbon & aramid fibers in milled, chopped, granulated, sized or un-sized form. In March 2018 Procotex Corporation sa acquired the assets of the company Herzog AG in Switzerland who had decades of experience in supplying mi...",
        "email": "info@procotex.com",
        "logo": "https://prelude.eurobrake.net/res/storage/exhibitor_Nouveau_logo_groupe_PROCOTEX.jpg",
        "configuration": "Shell scheme",
        "company": "Procotex Corporation sa / Apply Carbon sa"
      },
      {
        "country": "Germany",
        "website": "http://www.produco.eu",
        "booth": "70",
        "phone": "0049 (0) 4151 207 9020",
        "description": "PRODUCO GmbH means:\nConsulting\nDevelopment\nRationalization\nInnovation\nPRODUCO GmbH the innovative engine of the friction lining industry and offers the following achievement and product spectrum for friction lining industry and for raw material manufacturer:\n- Competent consultation with market development, raw material substitution, production - and pilot plant installation\n- Implementation of economical friction lining formulations\n- Project consultation, - co-operation, - support\n- Common dev...",
        "email": "reinhard@produco.eu",
        "logo": "https://prelude.eurobrake.net/res/storage/exhibitor_Produco_Logo.jpg",
        "configuration": "Shell scheme",
        "company": "Produco GmbH"
      },
      {
        "country": "China",
        "website": "http://www.br-graphite.com",
        "booth": "8",
        "phone": "+86 532 88893296",
        "description": "Producer of natural flake graphite,expandable graphite,spherical graphite,synthetice graphite for over 15 years.",
        "email": "sales@br-graphite.com",
        "logo": "https://prelude.eurobrake.net/res/storage/exhibitor__________logo__1.jpg",
        "configuration": "Space only",
        "company": "Qingdao Braide Graphite"
      },
      {
        "country": "Italy",
        "website": "http://www.quartzchem.com",
        "booth": "28",
        "phone": "+390255187284",
        "description": "Quartz S.r.l.s.u. is an Italian Company established in 1997 with Headquarter in Milan and production plants located nearby Milan (Italy) and in Bangkok (Thailand).\nThe Company has Certifications for ISO 9001:2015, ISO 14001:2015 and OHSAS 18001:2007. Production is mainly focused on Metal Sulfides I.e. Antimony Trisulfide, Zinc Sulfide, Tin Sulfides, Mixes of various ingredients, and recently, Titanates manufacturing.\nA R&D Team with experts in Friction and professional PhD scientists (both Chemi...",
        "email": "quartz@quartzchem.com",
        "logo": "https://prelude.eurobrake.net/res/storage/exhibitor_Quartz_LOGO_2016.jpg",
        "configuration": "Space only",
        "company": "QUARTZ S.R.L. SU"
      },
      {
        "country": "Italy",
        "website": "http://www.raicam.com",
        "booth": "80",
        "phone": "00390119371244",
        "description": "RAICAM develops and manufactures high quality brake pads for passenger cars and commercial vehicles. It is a reliable partner for the major car manufacturing industries, guaranteeing secure and comfortable breaks with its wide range of material formulations. Recently it has also developed LOW STEEL and NAO materials copper free, in accordance with the ‘Better Brakes Regulation’ (Chapter 173.901 WAC, 19/10/2012) and ‘California’s Brake Friction Material Law’ (Senate Bill n. 346, Chapter 307, 25/0...",
        "email": "crivoira@raicam.com",
        "logo": "https://prelude.eurobrake.net/res/storage/exhibitor_RAICAM_marchio_PO_4c_pos.jpg",
        "configuration": "Shell scheme",
        "company": "Raicam Industrie"
      },
      {
        "country": "Germany",
        "website": "http://www.reichmann.com",
        "booth": "9",
        "phone": "+49 7309 875 43",
        "description": "The Reichmann & Sohn GmbH is a German engineering company with 100 years of experience in cutting and grinding. The division Reichmann Casting Finishing is the world's leading supplier of machines for casting finishing and fettling technologies. A particular focus lays on automatic grinding systems for round parts such as brake discs and brake drums. Apart from that, Reichmann offers customer-tailored and innovative solutions for abrasive cutting and belt grinding. To ensure a further automatiza...",
        "email": "slojewski@reichmann.com",
        "logo": "https://prelude.eurobrake.net/res/storage/exhibitor_Reichmann_Casting_Finishing.jpg",
        "configuration": "Shell scheme",
        "company": "Reichmann & Sohn GmbH"
      },
      {
        "country": "Germany",
        "website": "http://www.renk-ag.com",
        "booth": "6",
        "phone": "+49 821 5700 0",
        "description": "RENK offers over 30 years experience of manufacturing high-quality test systems for drive-train components, brake-systems ad complete vehicles. Due to decades of experience in in-house R&D test equipment, today RENK is one of the leading manufacturers of customized test systems for the automotive, wind power, agricultural, aviation and railway industries.\nWorldwide, renowned OEMs take advantage of our extensive experience in drive technology, measuring technology, electronics and system design a...",
        "email": "info.testsystem@renk.biz",
        "logo": "https://prelude.eurobrake.net/res/storage/exhibitor_Logo_RENK_simple_black.jpg",
        "configuration": "Shell scheme",
        "company": "RENK Test System GmbH"
      },
      {
        "country": "Germany",
        "website": "http://www.richard-anton.de",
        "booth": "63",
        "phone": "+49 898981440",
        "description": "Richard Anton KG is one of the world’s leading suppliers of synthetic Graphite and calcined Petroleum Coke for brake linings. Our products can be found in nearly all types of vehicles. Founded in 1904 in Munich, the German company is still a 100% family-owned business which is now already managed by the 4th generation.\nIn our two plants in Germany we produce customised carbon products for nearly all major brake lining manufacturers worldwide. Since nearly 40 years Richard Anton KG has been speci...",
        "email": "klaus.wiesnet@richard-anton.de",
        "logo": "https://prelude.eurobrake.net/res/storage/exhibitor_Richard_Anton_KG.JPG",
        "configuration": "Shell scheme",
        "company": "Richard-Anton KG"
      },
      {
        "country": "Spain",
        "website": "http://www.rimsa.com",
        "booth": "24",
        "phone": "+34 93 666 46 11",
        "description": "Since 1985, we are leading manufacturers of non-ferrous materials, which are sold to more than 35 countries scattered across 5 continents.\nAt rimsa, we have been continuously developing innovative products which meet the highest standards and trends of the Global Friction Industry.\nThrough an intense R&D program, we have developed a state-of-the art technology to produce a wide range of synthetic metal sulfides, which can adapt to the specific requirements of our clients.\nWe use our knowledge an...",
        "email": "sales@rimsa.com",
        "logo": "https://prelude.eurobrake.net/res/storage/exhibitor_new_RIMSA_logo.jpg",
        "configuration": "Shell scheme",
        "company": "Rimsa Metal Technology SA"
      },
      {
        "country": "Germany",
        "website": null,
        "booth": "94",
        "phone": null,
        "description": "RTE has been working for the automotive industry for more than 30 years and is an expert in acoustic testing of brake components, especially for series production.\n\nThe main fields of RTE are:\n• Measurement and evaluation of natural frequencies of components \n• Acoustic material testing as quality check of components, such as crack testing, testing of material structure, based on acoustic resonance analysis\n• Noise and functional testing of components which generate noise during operation (motor...",
        "email": null,
        "logo": "https://prelude.eurobrake.net/res/storage/exhibitor_RTE_Akustik.jpg",
        "configuration": "Shell scheme",
        "company": "RTE Akustik + Prüftechnik GmbH"
      },
      {
        "country": "United States",
        "website": "https://rtec-instruments.com/",
        "booth": "41",
        "phone": "+1(408)7089226",
        "description": "Rtec-Instruments develops and manufactures advanced imaging and surface mechanical property measurement solutions for research and industrial applications. Based out of Silicon Valley, we are a leading provider of test instrumentation such as tribometer, optical profilometer, scratch tester, micro hardness tester etc. \n\nWe share a philosophy that embraces collaboration and partnering with customers and other leaders in academia and industry to ensure that our products answer real needs with inno...",
        "email": "info@rtec-instruments.com",
        "logo": "https://prelude.eurobrake.net/res/storage/exhibitor_RTEC_HD_logo.jpg",
        "configuration": "Space only",
        "company": "Rtec-Instruments,Inc"
      },
      {
        "country": "Spain",
        "website": "http://www.sadeca.com",
        "booth": "36",
        "phone": "+34 93 715 33 54",
        "description": "Sadeca is located in Barcelona and was founded on 1983. After these years of rigor, automotive passion and competitive spirit we have become a leader in cable manufacturing for the automotive industry.\nWe are specialized in the development, design and production of brake wear sensors, brake system hardware and several industrial wire harness applications for passenger cars, commercial vehicle and trucks for OEM/OES and AM segments.\nThanks to our quality standards, guaranteeing the compliance and...",
        "email": "sales@sadeca.net",
        "logo": "https://prelude.eurobrake.net/res/storage/exhibitor_sadeca__6_.jpg",
        "configuration": "Shell scheme",
        "company": "Sadeca Automotive, S.L.U."
      },
      {
        "country": "Germany",
        "website": "http://www.biolink-tapes.com",
        "booth": "67",
        "phone": "+49 (0)8021504290",
        "description": "Saint-Gobain Performance Plastics Tape Solutions offers solutions for bonding, protection and insulation to the automotive, transportation and other industry sectors.\n\nThrough the support of our four global research and development centers and our advanced polymer technology expertise, we create innovative solutions that enhance performance in the most extreme environments. Backed by a proud heritage of product innovation, technological expertise and market leadership, we are dedicated to workin...",
        "email": "jan.faltin@saint-gobain.com",
        "logo": "https://prelude.eurobrake.net/res/storage/exhibitor_Logo_SAINT_GOBAIN_CMJN.jpg",
        "configuration": "Space only",
        "company": "Saint-Gobain"
      },
      {
        "country": "Denmark",
        "website": "http://www.sbs.dk",
        "booth": "3",
        "phone": "+45 61 20 3808",
        "description": "Supplier of high-end brake pads for most major system suppliers in the OEM segment across all types of motor-cycles, scooters and ATV/UTV’s.\nSBS masters all brake pad technologies, ceramic/organic, open sinter, conductive sinter.\nDocumentation includes statistical process control methods and associated test and control equipment.",
        "email": "ejs@sbs.dk",
        "logo": "https://prelude.eurobrake.net/res/storage/exhibitor_SBS_GO_AHEAD_CMYK.jpg",
        "configuration": "Space only",
        "company": "SBS Friction A/S"
      },
      {
        "country": "Germany",
        "website": "http://www.stw-faser.de",
        "booth": "10",
        "phone": "+49 7836570",
        "description": "Schwarzwälder Textil-Werke Heinrich Kautzmann GmbH develops and produces high-quality fibres for different industries and applications. As leading specialists in fibre fillers, short cut fibres, fibrids & pulp, as well as customised solutions, we process all fibre materials; from natural fibres to synthetic fibres through to high-tech fibres. Thanks to decades of experience, continuous research and strong customer-orientation, we are able to react flexibly to new requirements with our bespoke fi...",
        "email": "info@stw-faser.de",
        "logo": "https://prelude.eurobrake.net/res/storage/exhibitor_STW_Logo_Farbe_RGB_Flat.jpg",
        "configuration": "Shell scheme",
        "company": "Schwarzwalder Textil-Werke Heinrich Kautzmann GmbH"
      },
      {
        "country": "China",
        "website": "http://www.brakechina.com",
        "booth": "11",
        "phone": null,
        "description": "Founded in 1990, Shandong Double Link Brake Material Co., Ltd is the leading friction materials manufacturer in China.\n\nOur major product lines include disc brake pads, drum brake linings, fine blanking & welding. With more than 2,000 references, we have been selling to the AM markets in North America, Europe, Australia, Middle East & South America. Double Link is the first Chinese friction materials OEM supplier to GM, Ford & FCA in North America since 2005, and we are also the OEM supplier to ...",
        "email": null,
        "logo": "https://prelude.eurobrake.net/res/storage/exhibitor_double_link_for_app.jpg",
        "configuration": "Shell scheme",
        "company": "Shandong Double Link Brake Material Co., Ltd"
      },
      {
        "country": "United States",
        "website": "http://www.sdk.co.jp/english/",
        "booth": "89",
        "phone": "+1 8438753200",
        "description": "Showa Denko Carbon, Inc. is a member of the Carbon Division of Showa Denko K. K., a global company using aluminum, inorganic and organic chemical technologies to provide industrial and consumer products for energy, automotive, information/telecommunication, and environmental applications. The Carbon Division manufactures graphite electrodes for electric steelmaking and graphite particles for vehicle (friction) and industrial applications.\n\nIn 2017, the Carbon division acquired SGL Carbon GE, mak...",
        "email": "sdkcgranular@sdkc.com",
        "logo": "https://prelude.eurobrake.net/res/storage/exhibitor_SDKK_Brand_Mark__JPEG_Image_File_.jpg",
        "configuration": "Shell scheme",
        "company": "Showa Denko Carbon, Inc."
      },
      {
        "country": "Germany",
        "website": "http://www.shw.de",
        "booth": "77",
        "phone": "+49 7361 502 1",
        "description": "The Company was established in 1365, making it one of the oldest industrial companies in Germany. Today, SHW AG is a leading automotive supplier, providing products that make a substantial contribution to reducing fuel consumption and, consequently, to lowering CO2 emissions. In its Pumps and Engine Components business segment, the SHW Group develops and produces pumps for passenger cars (including circuit boards) and Truck & Off-Highway applications (e.g., trucks, agricultural and construction ...",
        "email": "info@shw.de",
        "logo": "https://prelude.eurobrake.net/res/storage/exhibitor_shw_2.jpg",
        "configuration": "Space only",
        "company": "SHW Automotive"
      },
      {
        "country": "United States",
        "website": "http://www.speclubes.com",
        "booth": "57",
        "phone": "+18 002 385 823",
        "description": "Manufacturer and private label packager of Brake Lubricants that are proven to reduce NVH. Other products include brake assembly fluid and rotor cleaning solution.\nPrivate label packaging available in pouches, squeeze tubes, wipes and bulk containers.",
        "email": "ken@speclubes.com",
        "logo": "https://prelude.eurobrake.net/res/storage/exhibitor_Special_Lubricants.jpg",
        "configuration": "Space only",
        "company": "Speciality Lubricants Corporation"
      },
      {
        "country": "Germany",
        "website": "http://www.stac.de",
        "booth": "2",
        "phone": "+49 215 193 7270",
        "description": "STAC manufactures fast and precise NVH test systems, which are frequently used in automotive industry. STAC is featuring EVENTSCAN, a system for detecting and analyzing brake noise events. EVENTSCAN enables laboratory-based dynamometer tests as well as in-vehicle-tests on the road. The system acquires sound and vibration signals; other parameters like pressure, temperature, speed, etc. may be acquired via analogue inputs, CAN bus, GPS sensors, tachometer pulse inputs and others. All acquisition ...",
        "email": "info@stac.de",
        "logo": "https://prelude.eurobrake.net/res/storage/exhibitor_staclogo_hires_pms300.jpg",
        "configuration": "Shell scheme",
        "company": "STAC Elektronische Systeme GmbH"
      },
      {
        "country": "United States",
        "website": "http://www.sterlingfibers.com",
        "booth": "96",
        "phone": "001-850-994-5311",
        "description": "Sterling Fibers is an ISO 9001 certified USA based company serving the friction material industry since 1988. Sterling Fibers offers a variety of acrylic based fibers and pulps for the friction material industry:\n\n- Sterling’s flagship product, CFF V110 pulp, provides preforming ability equal to aramid at a much lower price. \n\n- Sterling’s CPF 200 series products offer lower cost alternatives to CFF V110. \n\n-Sterling’s CFF 100 series pulps are utilized in wet mixing processes such as friction pa...",
        "email": "customerservice@sterlingfibers.com",
        "logo": "https://prelude.eurobrake.net/res/storage/exhibitor_Sterling_Fibers.jpg",
        "configuration": "Shell scheme",
        "company": "Sterling Fibers"
      },
      {
        "country": "Sweden",
        "website": "https://superiorgraphite.com/",
        "booth": "26",
        "phone": "+46 60134188",
        "description": "Delivering unparalleled quality since 1917, Superior Graphite provides unique solutions for the friction market among others. FormulaFX™ materials utilize a variety of carbonaceous materials, from synthetic to crystalline flake graphite to calcined petroleum cokes, to offer a full spectrum of friction modifier materials, each with specialized performance and durability characteristics designed to meet specific industry requirements in every category. Resilient Graphitic Carbon™ (RGC™) materials ...",
        "email": "CustomerServiceEU@superiorgraphite.com",
        "logo": "https://prelude.eurobrake.net/res/storage/exhibitor_Superior_Graphite_Logo_Horizontal.jpg",
        "configuration": "Shell scheme",
        "company": "Superior Graphite"
      },
      {
        "country": "India",
        "website": "http://www.taprath.com",
        "booth": "91",
        "phone": "+91 22 2631 3185 / 86",
        "description": "Taprath combines the power of science and technology to passionately innovate and serve its partners. Taprath is one of the world’s leading suppliers of speciality Elastomer Powders, bio-soluble Mineral Fibres.\n\nOur Products include:\n1) Tapryl® - Nitrile Rubber Powders\na. Pre-crosslinked\nb. Crosslinked\nc. Branched\nd. Linear\n2) Taprene® - Styrene Butadiene Rubber Powders\n3) GeoWool® Mineral Fibres – Friction Applications\n4) GeoWool® SealOn Mineral Fibres – Gasket Applications\n\nWith 15 years of ex...",
        "email": "taprath@taprath.com",
        "logo": "https://prelude.eurobrake.net/res/storage/exhibitor_logo_taprath__1_.JPG",
        "configuration": "Shell scheme",
        "company": "Taprath Elastomers LLP"
      },
      {
        "country": "Germany",
        "website": "http://www.th-wildau.de",
        "booth": "100",
        "phone": "+49 3375 508 129",
        "description": "The University of Applied Sciences Wildau (TH Wildau), founded in 1991, is the largest technical university of applied sciences in the State of Brandenburg, Germany. Its modern campus located right next to Berlin at the motorway junction A10/A13, reachable by all modes of transport. As an educational and research institution, the TH Wildau does not only focus strongly in the capital region of Berlin-Brandenburg but also nationwide and internationally. The university’s hallmarks are its research ...",
        "email": "transfer@th-wildau.de",
        "logo": "https://prelude.eurobrake.net/res/storage/exhibitor_TH-Wildau-Logo_cmyk_356x142_300dpi.jpg",
        "configuration": "Space only",
        "company": "Technical University of Applied Sciences Wildau"
      },
      {
        "country": "Italy",
        "website": "http://www.tecsa-srl.it/index(en).html",
        "booth": "69",
        "phone": "+39 0119804001",
        "description": "We are manufacturer of Brake Inertia Dynamometers and test machines, we also do the Upgrade (electical, electronical, mechanical and system acquisition) of old test benches inasmuch as we have developed our own software.\nOur line of products includes test machines for quality control (Friction Quality Test machine, Shear Strength Test machine, Mini-Dyno) and dynamometers of various sizes (both for brakes and clutches) and other machines for automotive, truck, railway and planes tests.\nWe have al...",
        "email": "info@tecsa-srl.it",
        "logo": "https://prelude.eurobrake.net/res/storage/exhibitor_logoTECSA_HQ-Eurobrake.jpg",
        "configuration": "Shell scheme",
        "company": "TecSA S.r.l."
      },
      {
        "country": "Germany",
        "website": "http://www.teijinaramid.com",
        "booth": "51",
        "phone": "+49202322317",
        "description": "At Teijin Aramid, everything we do is guided by our ambition to shape a better future for generations to come. Day after day, we move forward, continuously improving our processes, our technology and ourselves. As market leaders, we drive progress through collaboration and set new standards for high performance. We connect with our customers at every level, wherever they are in the world. Because we believe that, together, we can be something bigger. Together, we can challenge conformity.\nFrom a...",
        "email": "contact_EMEA@teijinaramid.com",
        "logo": "https://prelude.eurobrake.net/res/storage/exhibitor_brandlogo-brandstatement1-JPEG.jpg",
        "configuration": "Space only",
        "company": "Teijin Aramid GmbH"
      },
      {
        "country": "Netherlands",
        "website": "http://www.morimura.co.jp/english/",
        "booth": "101",
        "phone": "+31 35 656 4564",
        "description": "TOHO MATERIAL CO, LTD was established in 2009 as a subsidiary of TOHO TITANIUM Co, Ltd, which has been leading titanium business in the world for more than 60 years.\nUtilizing titanium related technologies of its parent company, TOHO MATERIAL developed and introduced Potassium Titanate \"TOFIX\" for automotive function material. With our unique, efficient, and environmentally friendly production process, \"TOFIX\" series accomplished stable quality and high friction performance (good wear resistance...",
        "email": "info@morimura.nl",
        "logo": null,
        "configuration": "Shell scheme",
        "company": "TOHO MATERIAL CO.,LTD. / MORIMURA BROS. (EUROPE) B.V."
      },
      {
        "country": "Sweden",
        "website": "http://www.rubore.com",
        "booth": "1",
        "phone": "+46 480 499 400",
        "description": "Trelleborg Sealing Solutions Kalmar is the world leader in the production and development of brake noise and vibration damping solutions for automotive and industrial applications.\n\nOur main products are shims, but considerable achievements have been reached in sound damping of engine and chassis’ parts for the automotive OEM and industrial markets. We are the world leader in the innovation of new rubber to metal sandwich-composite materials and very successful in the world market with noise ins...",
        "email": "Kai.Koppers@Trelleborg.com",
        "logo": "https://prelude.eurobrake.net/res/storage/exhibitor_Trelleborg_40_RGB.jpg",
        "configuration": "Space only",
        "company": "Trelleborg Sealing Solutions Kalmar"
      },
      {
        "country": "Austria",
        "website": "http://www.tribotecc.at",
        "booth": "14",
        "phone": "+43 151256110",
        "description": "Tribotecc GmbH is the global market and technology leader of high performance metal sulfide solutions for the friction industry. The tribological properties of metal sulfide systems with regard to chemical structure, polarity, lubricating ability and thermal behavior are essential for the functioning and performance enhancement of friction products and help to extend the lifetime of components motion.\nSulfides of various metals have proven to be the most versatile and most effective additives fo...",
        "email": "office@tribotecc.at",
        "logo": "https://prelude.eurobrake.net/res/storage/exhibitor_Logo_Tribotecc.jpg",
        "configuration": "Shell scheme",
        "company": "Tribotecc GmbH"
      },
      {
        "country": "Germany",
        "website": "http://www.tsi.com",
        "booth": "98",
        "phone": "+49 241 523 030",
        "description": "As the international leader in aerosol instrumentation for over 50 years, TSI Incorporated designs and manufactures precision instruments which are recognized in research and industry worldwide to perform advanced and reliable particle measurements such as brake wear emissions.\n\nStop by our booth to discuss about your research and measurements. TSI has unique, fast size distribution solutions for conducting brake wear emissions testing: Engine Exhaust Particle Sizer (EEPS) and the 10 Hz Optical ...",
        "email": "tsi.emea@tsi.com",
        "logo": "https://prelude.eurobrake.net/res/storage/exhibitor_TSI-black.jpg",
        "configuration": "Shell scheme",
        "company": "TSI GmbH"
      },
      {
        "country": "Germany",
        "website": "http://www.waldraff.info",
        "booth": "64 & 65",
        "phone": "+49 221 949 9530",
        "description": "Partner of Automotive Industries Planning, design and production of custom-made solutions for the automotive industry and their suppliers.\n\nMachine manufacturing: Shot blasting technology / Coating technology / Materials handling technology / Production lines / Assembly lines / Measurement and test engineering / Automation technology/Handling technology / Manual workstations/Assisting devices / Special machinery Tool manufacturing / Pressing tools (pads for disk brakes) / Specific production too...",
        "email": "rick@waldraff.info",
        "logo": "https://prelude.eurobrake.net/res/storage/exhibitor_WT-3D-Logo-rz-final_2011_verkleinert.JPG",
        "configuration": "Space only",
        "company": "WALDRAFF Technologies GmbH & Co. KG"
      },
      {
        "country": "Germany",
        "website": "http://www.walter-werner.de",
        "booth": "61",
        "phone": "+49 678299320",
        "description": "Walter Werner for a better finish\nYour certified specialist for metal finishing.\nOur process portfolio yields decorative surfaces and protects metals and plastics against corrosion and wear. Our business segments are electroplating, coating and bonding agent coatings. Certified under IATF 16949, AIAG and registered with EMAS II, our company applies environmentally friendly production processes for audited product quality each and every time.\nWalter Werner GmbH has been renowned for its professio...",
        "email": "info@walter-werner.de",
        "logo": "https://prelude.eurobrake.net/res/storage/exhibitor_WalterWerner_rot-grau.jpg",
        "configuration": "Shell scheme",
        "company": "Walter Werner GmbH"
      },
      {
        "country": "Germany",
        "website": "http://www.weckerle.de",
        "booth": "5",
        "phone": "+49 711 82601 0",
        "description": "Weckerle Lackfabrik GmbH is a medium-sized company with staff of about 70. Since its founding in 1908 Weckerle develops and produces a wide range of high performance and innovative coating systmes for many different tasks and area of applications.\n\nFrom its founding until being sold in 2000 Weckerle was exclusively a family business. This is still noticeable today - even after being sold to a group of investors in 2000 and to the Berlac Group in 2011. This is thanks to the management policy whic...",
        "email": "info@weckerle-lacke.de",
        "logo": "https://prelude.eurobrake.net/res/storage/exhibitor_9244_Weckerle_Logo_131117.jpg",
        "configuration": "Shell scheme",
        "company": "Weckerle Lackfabrik GmbH"
      },
      {
        "country": "China",
        "website": "http://www.winhere.com.cn",
        "booth": "20",
        "phone": "+86 532 857 611 11",
        "description": "Founded in 1996, Winhere is the largest professional manufacturer of brake discs and drums in China. \nWinhere is TS16949 quality certified by TUV Rheinland, we produce more than 5,000 applications with 44 million unit’s annual capacity to service our customers globally.\n\nWinhere has received the world’s first ECE R90 certificate issued by KBA in Germany since August 2012, and we are extending full range of our brake discs and drums with R90 certified.\n\nWinhere won gold award of “Best-In-Class” f...",
        "email": "Autoparts@winhere.com.cn",
        "logo": null,
        "configuration": "Shell scheme",
        "company": "Winhere Auto-Part Manufacturing"
      },
      {
        "country": "United States",
        "website": "http://www.wamglobal.com",
        "booth": "90",
        "phone": "1 (313)749 6100",
        "description": "Wolverine Advanced Materials is a leading developer and manufacturer of high-performance materials. Our core competency is in performance-critical, specialty elastomer-coated metals that offer damping and sealing solutions in the Automotive Brake NVH, and Sealing industries. Extensive industry knowledge and innovative materials have made Wolverine a desired and trusted global supplier for over 80 years.",
        "email": "inquiry.automotive@wamglobal.com",
        "logo": "https://prelude.eurobrake.net/res/storage/exhibitor_Wolverine_No-EP.jpg",
        "configuration": "Space only",
        "company": "Wolverine Advanced Materials"
      },
      {
        "country": "China",
        "website": "http://www.zhongbanggongju.com",
        "booth": "47",
        "phone": "0086 371 86076765",
        "description": "Zhengzhou Zhongbang Superhard Tools co,.ltd established in 1990, locates in the biggest grinding material and grinding tool base – Zhengzhou. We are mumber unite of CFSMA and CMTBA. We have dedicated to the research& development of the superhard grinding tools for many years. Expand from a small to a large force, from extensive to intensive, we build up perfect manufacture and quality control system. We own many advanced producing and inspecting machines, such as high precision CNC lathe, high p...",
        "email": "nancy.y@zhongbanggongju.com",
        "logo": "https://prelude.eurobrake.net/res/storage/exhibitor___9YKVCK36TB_ZPW26_QFYD.jpg",
        "configuration": "Shell scheme",
        "company": "Zhengzhou Zhongbang Superhard tools co ltd"
      },
      {
        "country": "China",
        "website": "http://www.zhglory.com",
        "booth": "97",
        "phone": "+86 134 250 858 69",
        "description": "Glory was founded in 1986, its headquarters’ R&D center and main production base located in Zhuhai,China.Glory is professional automobile braking friction materials company. There are nearly 60 engineers work for R&D center today with globally braking field rich experience experts from China, Germany, Japan and US. The main products are automobile using braking pad, braking lining, and brake block for OEM market and Global aftermarket including US, European, Asia, Pacific, etc with 10 Million ca...",
        "email": "doris.guan@zhglory.com.cn",
        "logo": "https://prelude.eurobrake.net/res/storage/exhibitor_GLORY_logo.jpg",
        "configuration": "Shell scheme",
        "company": "Zhuhai Glory Friction Material Co., Ltd."
      },
      {
        "country": "China",
        "website": "http://www.u-metal.cn",
        "booth": "66",
        "phone": "+86 756 8817016",
        "description": "Zhuhai UniMetal Co. Ltd., engages in metallic wool fibers to friction industries, satisfies their applications of brake pads/lining manufacturing. \n\n*Steel Wool Fiber - 5 Production Lines - Annual Capacity 7000MT \n*Copper/Brass/Bronze/Aluminum Wool Fiber - 7 Production lines - Annual Capacity 650MT \n\nOur metallic wool fibers are certified by IATF16949:2016. Selected material, excellent product consistency, good quality and professional service make us your first choice of supplier for OE product...",
        "email": "sales@u-metal.cn",
        "logo": "https://prelude.eurobrake.net/res/storage/exhibitor_LOGO.jpg",
        "configuration": "Shell scheme",
        "company": "Zhuhai Unimetal Co., Limited"
      }
 ];